AllCops:
  Exclude:
    - db/**
    - config/**
    - script/**
    - node_modules/**/*
    - test/**/*
    - bin/bundle


Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 40